# name of our action
name: 'Storybook Deployment on Chromatic'
# the event that will trigger the action
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn && yarn build
    - uses: chromaui/action@v1
      with: 
        # refer to https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/
        # https://github.com/chromaui/action
        projectToken: ${{ secrets.CHROMATIC_TOKEN }}
        token: ${{ secrets.GIT_TOKEN }}